### ISSUE TITLE
Task 1 review

### ISSUE THREAD

**Issue by jokerjunjie** [minyi2105/Task-1#1]
<h2>Minor mistake</h2>

if the code does not got any usage , can remove it.

https://github.com/minyi2105/Task-1/blob/b7d1bdb23f4abb22645df102cbe9f6f35f1c7db0/app/src/main/java/com/example/fourtitudetask1/activities/DummyDetailActivity.java#L34-L38

https://github.com/minyi2105/Task-1/blob/b7d1bdb23f4abb22645df102cbe9f6f35f1c7db0/app/src/main/java/com/example/fourtitudetask1/adapters/DummyAdapter.java#L71

https://github.com/minyi2105/Task-1/blob/b7d1bdb23f4abb22645df102cbe9f6f35f1c7db0/app/src/main/java/com/example/fourtitudetask1/model/Dummy.java#L83-L86

______________________

Redundant initialize UI component.

https://github.com/minyi2105/Task-1/blob/b7d1bdb23f4abb22645df102cbe9f6f35f1c7db0/app/src/main/java/com/example/fourtitudetask1/activities/MainActivity.java#L35

https://github.com/minyi2105/Task-1/blob/b7d1bdb23f4abb22645df102cbe9f6f35f1c7db0/app/src/main/java/com/example/fourtitudetask1/activities/MainActivity.java#L23
_____________

The RecyclerViewHolderView can actually using butterknife

____________

<h2>Missing Requirement </h2>

> The listing page should display at least 20 items that are unique to each other

**Comment by minyi2105** [comment]
The stated mistakes have been fixed.
